### ISSUE TITLE
No more IA in car after exiting garage

### ISSUE THREAD

**Issue by TheFahren** [ESX-Org/esx_garage#12]
Hi, 
When I come out of the garage by car or on foot, there is no AI car only AI walking.
It seems to be an instance problem.

Btw Thanks a lot for this script.

**Comment by ElPumpo** [comment]
Must be related to instance, I'll check on it...

**Comment by hacklover** [comment]
Same here

**Comment by ElPumpo** [comment]
Fixed in https://github.com/ESX-Org/instance/commit/72a733747b967aadd490fa39e9ea597dad2960b8, update instance and report back.

**Comment by TheFahren** [comment]
Thx a lot for the release and the help.

Bye

2018-05-22 20:00 GMT+02:00 Samuel <notifications@github.com>:

**Comment by ElPumpo** [comment]
Then close the issue?
